[2024-08-07T14:59:06.140+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:59:06.182+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-space-exploration.Respuesta_Satelite scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-08-07T14:59:06.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-space-exploration.Respuesta_Satelite scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-08-07T14:59:06.207+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-08-07T14:59:06.234+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Respuesta_Satelite> on 2024-08-03 00:00:00+00:00
[2024-08-07T14:59:06.243+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:59:06.246+0000] {standard_task_runner.py:64} INFO - Started process 151 to run task
[2024-08-07T14:59:06.246+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***-space-exploration', 'Respuesta_Satelite', 'scheduled__2024-08-03T00:00:00+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmpll8zqn7i']
[2024-08-07T14:59:06.249+0000] {standard_task_runner.py:91} INFO - Job 328: Subtask Respuesta_Satelite
[2024-08-07T14:59:06.322+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow-space-exploration.Respuesta_Satelite scheduled__2024-08-03T00:00:00+00:00 [running]> on host 38873943cc86
[2024-08-07T14:59:06.458+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-space-exploration' AIRFLOW_CTX_TASK_ID='Respuesta_Satelite' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-03T00:00:00+00:00'
[2024-08-07T14:59:06.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:59:07.689+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-07T14:59:07.690+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:59:07.702+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=***-space-exploration, task_id=Respuesta_Satelite, run_id=scheduled__2024-08-03T00:00:00+00:00, execution_date=20240803T000000, start_date=20240807T145906, end_date=20240807T145907
[2024-08-07T14:59:07.750+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T14:59:07.788+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:59:07.791+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
